// src/store/notifications/notificationTypes.js
export const GET_NOTIFICACIONES_REQUEST = 'GET_NOTIFICACIONES_REQUEST';
export const GET_NOTIFICACIONES_SUCCESS = 'GET_NOTIFICACIONES_SUCCESS';
export const GET_NOTIFICACIONES_FAILURE = 'GET_NOTIFICACIONES_FAILURE';
export const ELIMINAR_NOTIFICACION = 'ELIMINAR_NOTIFICACION';
