type Receta = {
  id: number;
  litrosEstimados: number;
  precioUnitarioMinimoMayoreo?: number;
  precioUnitarioBaseMayoreo?: number;
  porcentajeDescuento?: number;
  precioLitro?: number;
  precioPaquete1?: number;
  precioPaquete6?: number;
  precioPaquete12?: number;
  precioPaquete24?: number;
  lotesMinimos?: number;
  lotesMaximos?: number;
  puntuacion?: number;
  especificaciones?: string;
  descripcion?: string;
  nombre: string;
  costoProduccion: number;
  imagen: string;
  rutaFondo?: string;
  tiempoVida: number;
  activo: boolean;
  fechaRegistrado: string;
};
